### ISSUE TITLE
'Variables' button does not provide possible options

### ISSUE THREAD

**Issue by Gasman2014** [pioupus/kicadLibCreator#31]
I am trying to add rules and I have some (like value, mpn, manufacturer etc) working. When i click on the 'Variables' button, I would expect to see a list of possible options (as per the ReadMe)

> For each field there is a text box which you can fill with text or variables. For knowing which variables exist, there is a variable button besides the text box. A window with a list of variable-value pairs appears.  

This does not appear to work for me. For instance, I would like to add the ID and the pop up window shows %rule.name% and the name of the rule and two blank boxes.

![screen shot 2016-12-10 at 18 39 55](https://cloud.githubusercontent.com/assets/8401593/21075373/1983890c-bf08-11e6-97c8-77ca6b790ea3.png)

So it has been pretty much guesswork as to what might work :)

Might I suggest that the global rule come ready populated with ID, Datasheet, MPN and manufacturer? These would seem pretty standard and if anyone didn't want them it would be easy to edit.

Also, the rules do not survive a crash :(  - this can be triggered by clicking on the 'Source Device - 'Add' button' for instance.

**Comment by pioupus** [comment]
You have to open the rules window from the context of the 3rd tab. Because only then the program knows the specifications of the part. You have to click on the edit button besides the rulename combobox of the 3rd tab.

**Comment by Gasman2014** [comment]
Got it. Thank you - sorry for all the questions and not much input. Sorry, I am not any sort of programmer and QT / C++ is a step too far for me!

Hesitate to ask but I have 3 other questions;

1. How do I add a data sheet (F3) to the library creation page? I can't find any reference/link to 'datasheet' in the possible completion options. I have read the Octopart API too but can't find a reference there either. The link to the Octopart sheets seems to be a composite url of the form datasheets.octopart.com/mpn-manufacturer-datsheet-uid.pdf. Do you just construct the url somehow?

2. I have populated the necessary fields in the KiCad lib create tab. I can select the library that I want to save the component in in the bottom combo box, however, when I press 'create', no file is saved. Do I have to create blank, default entries for 'key', man, manufacturer & display value (as per your screen_kicad.png)?

3. In the second screen (KiCad input library) there  is no reference in the top bar area confirming the correct library (cf your 'screen_source.png - where there is `device.lib/C(capacitor_mlcc)`  in the upper area. I have already selected a single item from the octopart search.

![screen shot 2016-12-10 at 20 24 57](https://cloud.githubusercontent.com/assets/8401593/21075968/b1f61cfe-bf17-11e6-9cf2-bbe22e2191ad.png)

**Comment by pioupus** [comment]
Dont hesitate to ask! It is quite important that somebody tests the program :-) 

> 1 datasheet:

The path you specify in the datasheet field is the target path where the datasheet is downloaded to. I would recommend something like `%rule.name%/%octo.manufacturer.saveFilename%/%octo.mpn.saveFilename%.pdf`. When you click on download or create the datasheet should be downloaded in that folder relative to the datasheet path in the settings menu. 

> 2 creation:

A library with the name specified in the bottom combox should be created in the folder "target path"  of the settings window. The path and file should be created automatically. The part will have the name as the def/f1 field value. I have not tested what happens if the fields you mention are empty.

> 3, link in in input tab:

The reason why you don't see any link in the top part of the window is that you have no rule defined yet which A is linked to the octopart category of the queried octopart part and B has no source device defined.
To do this: select an octopart part, a symbol and enter the kicad lib creation tab. There you have to clikc on the edit button. In the rules window you find the category and source device tab with proposed categories/ source devices. A double click on the proposed item will link the rule to the category or device.


Thank you by the way for finding the crash which happens when you click on the source device's add button when no proposed device is selected. If you observe more crashes please tell me.

**Comment by pioupus** [comment]
by the way: there is an example rule file in the root path which might help you: `partCreationRules.ini` copy this file in the execution directory of the lib creator.

**Comment by Gasman2014** [comment]
Thank you. Sorry I am not more able to help by contributing to your code but hopefully my questions will help address the problems a newbie might have!

1. Datasheet
Thank you - that works. In fact it had worked before but i hadn't noticed the new directory pop up in my datasheet folder. However, when you click on 'Show' I would expect to either open the data sheet or at least shown it in the directory explorer - neither of which happens.

2. Library creation
Unfortunately, even when all of the fields are populated, when I click 'Create' nothing happens. I have tried both with and without a pre-existing *.lib file.

3. Link in 'Input tab'.
Strange problem here. When I go back to this tab, I notice that the list of possible libraries has been duplicated. If I click on the copy of the library lower in the list the application exits.

BW
